name: full-check

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]

    steps:
    - uses: actions/checkout@v4
    - name: install_dependencies
      run: sudo apt install libncurses-dev
    - name: first_build
      run: |
           ./autogen.sh
           ./configure
           make
           sudo make install
           sudo make uninstall
           make distclean 
    - name: second_build
      run: |
           ./autogen.sh
           ./configure
           make
           sudo make install
    - name: run_program
      run: |
           cbm --version

